import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type RuntimeConfig = { ipos_authorization:string|null; ipos_access_token:string|null; cron_secret:string|null; company_uid:string; brand_uid:string; city_uid:string; store_uid:string; store_name:string; org_id:string; warehouse_id:string; };
type CatalogRecord = Record<string, unknown> & { id?:string; item_id?:string; item_name?:string; };
type IposSale = { tran_id?:string; tran_no?:string; tran_date?:number; sale_updated_at?:number; store_uid?:string; deleted?:boolean; sale_detail?:unknown[]; total_amount?:number; [key:string]:unknown; };
type WindowedSale = IposSale & { __sync_start:number; __sync_end:number; };

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const TIME_ZONE_OFFSET_MS=7*60*60*1000;
const MAX_PAGES=100;
const SALE_DETAIL_CONCURRENCY=5;

function jsonResponse(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});}
function serviceHeaders():HeadersInit{return {apikey:SERVICE_ROLE_KEY,authorization:`Bearer ${SERVICE_ROLE_KEY}`,"content-type":"application/json"};}
async function rpc<T>(name:string,payload:Record<string,unknown>):Promise<T>{const response=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:serviceHeaders(),body:JSON.stringify(payload)});if(!response.ok){const detail=(await response.text()).slice(0,1000);throw new Error(`Supabase RPC ${name} failed (${response.status}): ${detail}`);}return await response.json() as T;}
function canonicalTranId(raw:unknown):string{const value=String(raw??"").trim();const match=/^EDT_(.+)_[0-9]+$/.exec(value);return match?.[1]??value;}
function localDayWindow(dayOffset=0){const shifted=new Date(Date.now()+TIME_ZONE_OFFSET_MS);const utcStart=Date.UTC(shifted.getUTCFullYear(),shifted.getUTCMonth(),shifted.getUTCDate()+dayOffset)-TIME_ZONE_OFFSET_MS;return {start:utcStart,end:utcStart+24*60*60*1000-1000,label:new Date(utcStart+TIME_ZONE_OFFSET_MS).toISOString().slice(0,10)};}
function localDayWindowForLabel(label:string){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(label);if(!match)throw new Error("sync_date must use YYYY-MM-DD");const year=Number(match[1]),month=Number(match[2]),day=Number(match[3]);const localMidnightAsUtc=Date.UTC(year,month-1,day);const parsed=new Date(localMidnightAsUtc);if(parsed.getUTCFullYear()!==year||parsed.getUTCMonth()!==month-1||parsed.getUTCDate()!==day)throw new Error("sync_date is not a valid calendar date");const utcStart=localMidnightAsUtc-TIME_ZONE_OFFSET_MS;return {start:utcStart,end:utcStart+24*60*60*1000-1000,label};}
function salesFromPayload(payload:unknown):IposSale[]{if(Array.isArray(payload))return payload as IposSale[];if(payload&&typeof payload==="object"){const record=payload as Record<string,unknown>;for(const key of ["data","result","items","sales"])if(Array.isArray(record[key]))return record[key] as IposSale[];}throw new Error("Unexpected iPOS response: sales array not found");}
function saleFromPayload(payload:unknown):IposSale{if(payload&&typeof payload==="object"){const data=(payload as Record<string,unknown>).data;if(data&&typeof data==="object"&&!Array.isArray(data))return data as IposSale;}throw new Error("Unexpected iPOS response: sale detail not found");}
function arrayFromPayload(payload:unknown):CatalogRecord[]{if(Array.isArray(payload))return payload as CatalogRecord[];if(payload&&typeof payload==="object"){const data=(payload as Record<string,unknown>).data;if(Array.isArray(data))return data as CatalogRecord[];}throw new Error("Unexpected iPOS catalog response: data array not found");}
async function loadConfig(){return await rpc<RuntimeConfig>("ly_ipos_get_runtime_config",{});}
function iposHeaders(config:RuntimeConfig):HeadersInit{return {accept:"application/json, text/plain, */*",authorization:config.ipos_authorization!,access_token:config.ipos_access_token!,fabi_type:"pos-cms",origin:"https://fabi.ipos.vn",referer:"https://fabi.ipos.vn/","accept-language":"vi","x-client-timezone":String(TIME_ZONE_OFFSET_MS)};}
async function fetchCatalogEndpoint(config:RuntimeConfig,endpoint:string){const url=new URL(`https://posapi.ipos.vn/api/mdata/v1/${endpoint}`);url.searchParams.set("skip_limit","true");url.searchParams.set("company_uid",config.company_uid);url.searchParams.set("brand_uid",config.brand_uid);url.searchParams.set("city_uid",config.city_uid);const response=await fetch(url,{headers:iposHeaders(config)});if(!response.ok){const detail=(await response.text()).slice(0,1000);throw new Error(`iPOS catalog ${endpoint} failed (${response.status}): ${detail}`);}return arrayFromPayload(await response.json());}
async function syncCatalog(config:RuntimeConfig){const [items,types,classes,units]=await Promise.all([fetchCatalogEndpoint(config,"items"),fetchCatalogEndpoint(config,"item-types"),fetchCatalogEndpoint(config,"item-classes"),fetchCatalogEndpoint(config,"units")]);const typeByUid=new Map(types.map(e=>[String(e.id??""),e]));const classByUid=new Map(classes.map(e=>[String(e.id??""),e]));const unitByUid=new Map(units.map(e=>[String(e.id??""),e]));const normalized=items.map(item=>{const type=typeByUid.get(String(item.item_type_uid??""));const itemClass=classByUid.get(String(item.item_class_uid??""));const unit=unitByUid.get(String(item.unit_uid??""));return {item_id:item.item_id,item_name:item.item_name,ots_price:item.ots_price,ta_price:item.ta_price,active:item.active,deleted:item.deleted,item_type_id:type?.item_type_id??null,item_type_name:type?.item_type_name??null,item_class_id:itemClass?.item_class_id??null,item_class_name:itemClass?.item_class_name??null,unit_id:unit?.unit_id??null,unit_name:unit?.unit_name??null};});return await rpc<Record<string,unknown>>("ly_ipos_upsert_products",{p_org_id:config.org_id,p_warehouse_id:config.warehouse_id,p_items:normalized});}
async function fetchSaleDetail(config:RuntimeConfig,saleHeader:IposSale,start:number,end:number){if(!saleHeader.tran_id)throw new Error("iPOS sale is missing tran_id");const url=new URL("https://posapi.ipos.vn/api/v1/reports/sales/get-sale-by-tran-id");for(const [k,v] of [["company_uid",config.company_uid],["brand_uid",config.brand_uid],["store_uid",config.store_uid],["start_date",String(start)],["end_date",String(end)],["tran_id",saleHeader.tran_id]])url.searchParams.set(k,v);const response=await fetch(url,{headers:iposHeaders(config)});if(!response.ok){const detail=(await response.text()).slice(0,1000);throw new Error(`iPOS sale detail failed (${response.status}): ${detail}`);}const detailed=saleFromPayload(await response.json());return {...saleHeader,...detailed,deleted:saleHeader.deleted===true||detailed.deleted===true};}
async function fetchSaleHeadersForDay(config:RuntimeConfig,start:number,end:number){const all:WindowedSale[]=[];const seen=new Set<string>();for(let page=1;page<=MAX_PAGES;page++){const url=new URL("https://posapi.ipos.vn/api/reports_v1/v3/pos-cms/report/sale-by-date");for(const [k,v] of [["company_uid",config.company_uid],["brand_uid",config.brand_uid],["store_uid",config.store_uid],["page",String(page)],["start_date",String(start)],["end_date",String(end)],["sort","dsc"],["store_open_at","0"]])url.searchParams.set(k,v);const response=await fetch(url,{headers:iposHeaders(config)});if(!response.ok){const detail=(await response.text()).slice(0,1000);throw new Error(`iPOS request failed (${response.status}): ${detail}`);}const pageSales=salesFromPayload(await response.json());if(pageSales.length===0)break;const signature=pageSales.map(s=>s.tran_id??"").join("|");if(seen.has(signature))break;seen.add(signature);all.push(...pageSales.map(sale=>({...sale,__sync_start:start,__sync_end:end})));}const unique=new Map<string,WindowedSale>();for(const sale of all)if(sale.tran_id)unique.set(sale.tran_id,sale);return [...unique.values()];}
async function fetchChangedSaleDetails(config:RuntimeConfig,headers:WindowedSale[]){const detailed:IposSale[]=[];for(let i=0;i<headers.length;i+=SALE_DETAIL_CONCURRENCY){const batch=headers.slice(i,i+SALE_DETAIL_CONCURRENCY);detailed.push(...await Promise.all(batch.map(sale=>fetchSaleDetail(config,sale,sale.__sync_start,sale.__sync_end))));}return detailed;}
async function recordAttempt(config:RuntimeConfig,values:{success:boolean;error?:string}){const now=new Date().toISOString();const payload:Record<string,unknown>={org_id:config.org_id,store_uid:config.store_uid,last_attempt_at:now,updated_at:now,last_error:values.success?null:(values.error??"Unknown error").slice(0,2000)};if(values.success)payload.last_success_at=now;const response=await fetch(`${SUPABASE_URL}/rest/v1/ly_ipos_sync_state?on_conflict=org_id,store_uid`,{method:"POST",headers:{...serviceHeaders(),prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload)});if(!response.ok)console.error("Could not record iPOS sync state",response.status,(await response.text()).slice(0,500));}

Deno.serve(async request=>{if(request.method!=="POST")return jsonResponse({error:"Method not allowed"},405);if(!SUPABASE_URL||!SERVICE_ROLE_KEY)return jsonResponse({error:"Supabase runtime configuration is unavailable"},500);let config:RuntimeConfig;try{config=await loadConfig();}catch(error){return jsonResponse({error:error instanceof Error?error.message:String(error)},500);}if(!config.cron_secret||request.headers.get("x-ly-cron-secret")!==config.cron_secret)return jsonResponse({error:"Unauthorized"},401);if(!config.ipos_authorization||!config.ipos_access_token)return jsonResponse({error:"iPOS credentials are not configured",store:config.store_name},503);
try{let body:Record<string,unknown>={};try{body=await request.json() as Record<string,unknown>;}catch{}const localNow=new Date(Date.now()+TIME_ZONE_OFFSET_MS);const requestedDate=typeof body.sync_date==="string"?body.sync_date:null;const force=body.force===true;const shouldSyncCatalog=body.sync_catalog===true||(!requestedDate&&localNow.getUTCMinutes()%15===0);const catalog=shouldSyncCatalog?await syncCatalog(config):null;if(body.catalog_only===true)return jsonResponse({ok:true,store:config.store_name,catalog,sales_upserted:0,sales_deleted:0,inventory_changed:false});const currentWindow=requestedDate?localDayWindowForLabel(requestedDate):localDayWindow(0);const windows=[currentWindow];if(!requestedDate&&localNow.getUTCHours()===0&&localNow.getUTCMinutes()<10)windows.push(localDayWindow(-1));const fetched=(await Promise.all(windows.map(w=>fetchSaleHeadersForDay(config,w.start,w.end)))).flat();const unique=new Map<string,WindowedSale>();for(const sale of fetched)if(sale.tran_id&&sale.store_uid===config.store_uid)unique.set(sale.tran_id,sale);const current=[...unique.values()];const deletedSales=current.filter(s=>s.deleted===true);const activeRaw=current.filter(s=>s.deleted!==true);let salesDeleted=0;for(const sale of deletedSales){const result=await rpc<Record<string,unknown>>("ly_ipos_delete_sale",{p_org_id:config.org_id,p_raw_tran_id:sale.tran_id,p_sale_updated_at:sale.sale_updated_at??null});if(result.deleted===true)salesDeleted++;}
const activeByCanonical=new Map<string,WindowedSale>();for(const sale of activeRaw){const key=canonicalTranId(sale.tran_id);const prior=activeByCanonical.get(key);if(!prior||Number(sale.sale_updated_at??sale.tran_date??0)>=Number(prior.sale_updated_at??prior.tran_date??0))activeByCanonical.set(key,sale);}const activeHeaders=[...activeByCanonical.values()];const changedIds=force?activeHeaders.map(s=>String(s.tran_id)):await rpc<string[]>("ly_ipos_changed_sale_ids",{p_org_id:config.org_id,p_sales:activeHeaders.map(s=>({tran_id:s.tran_id,sale_updated_at:s.sale_updated_at??null}))});const changedSet=new Set(changedIds);const changedHeaders=activeHeaders.filter(s=>changedSet.has(String(s.tran_id)));const sales=(await fetchChangedSaleDetails(config,changedHeaders)).sort((a,b)=>Number(a.sale_updated_at??a.tran_date??0)-Number(b.sale_updated_at??b.tran_date??0));let itemLines=0,withoutRecipe=0,inventoryChanged=false;for(const sale of sales){const result=await rpc<Record<string,unknown>>("ly_ipos_upsert_sale_with_inventory",{p_org_id:config.org_id,p_warehouse_id:config.warehouse_id,p_sale:sale});if(!String(result.sale_id??''))throw new Error('iPOS sync did not return a sale id');itemLines+=Number(result.items??0);withoutRecipe+=Number(result.items_without_recipe??0);inventoryChanged=inventoryChanged||Boolean(result.inventory_changed);}
let reconciliation:Record<string,unknown>|null=null;if(!requestedDate&&windows.length===1){reconciliation=await rpc<Record<string,unknown>>("ly_ipos_reconcile_absent_sales",{p_org_id:config.org_id,p_store_uid:config.store_uid,p_day:currentWindow.label,p_active_tran_ids:[...activeByCanonical.keys()]});if(reconciliation.deleted===true)salesDeleted++;}
await recordAttempt(config,{success:true});return jsonResponse({ok:true,store:config.store_name,catalog,windows:windows.map(w=>w.label),sale_headers_fetched:fetched.length,sale_details_fetched:sales.length,sales_unchanged:activeHeaders.length-sales.length,sales_upserted:sales.length,sales_deleted:salesDeleted,deleted_sales_seen:deletedSales.length,reconciliation,item_lines_upserted:itemLines,item_lines_without_recipe:withoutRecipe,inventory_changed:inventoryChanged});}catch(error){const message=error instanceof Error?error.message:String(error);await recordAttempt(config,{success:false,error:message});console.error("iPOS sync failed",message);return jsonResponse({ok:false,store:config.store_name,error:message},502);}});
