-- V190 - Atomic sales + inventory
create extension if not exists pgcrypto;

alter table public.sales add column if not exists note text;

-- Chạy 1 lần trong Supabase > SQL Editor.
-- Yêu cầu các bảng hiện có: sales, sale_items, stock_transactions, inventory.

create table if not exists public.app_operation_log (
  idempotency_key text primary key,
  operation_type text not null,
  reference_id uuid,
  operation_revision bigint generated by default as identity,
  result jsonb,
  created_at timestamptz not null default now()
);

alter table public.app_operation_log enable row level security;

drop policy if exists "app_operation_log_select" on public.app_operation_log;
create policy "app_operation_log_select"
on public.app_operation_log
for select
to anon, authenticated
using (true);

grant select on public.app_operation_log to anon, authenticated;

create or replace function public.commit_sale_receipt_v190(
  p_sale jsonb,
  p_sale_items jsonb,
  p_stock_movements jsonb,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale_id uuid;
  v_warehouse_id uuid;
  v_existing jsonb;
  v_old_qty numeric;
  v_new record;
  v_delta numeric;
  v_result jsonb;
  v_sale_row jsonb;
  v_items jsonb;
  v_movements jsonb;
  v_inventory jsonb;
  v_operation_revision bigint;
begin
  if p_idempotency_key is null or length(trim(p_idempotency_key)) < 6 then
    raise exception 'Invalid idempotency key';
  end if;

  v_sale_id := (p_sale->>'id')::uuid;
  v_warehouse_id := (p_sale->>'warehouse_id')::uuid;

  -- Serialize all retries / concurrent commits for the same sale.
  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key, 0));

  select result
  into v_existing
  from public.app_operation_log
  where idempotency_key = p_idempotency_key;

  -- For CREATE retry, return same committed result.
  -- For EDIT we allow recomputation when payload changed; operation log is replaced below.
  if v_existing is not null
     and coalesce(v_existing->>'payload_hash','') =
         encode(digest(
           coalesce(p_sale::text,'') ||
           coalesce(p_sale_items::text,'') ||
           coalesce(p_stock_movements::text,''),
           'sha256'
         ), 'hex')
  then
    return v_existing - 'payload_hash';
  end if;

  -- Lock affected inventory rows deterministically to avoid deadlocks.
  perform 1
  from public.inventory i
  where i.warehouse_id = v_warehouse_id
    and i.ingredient_id in (
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_stock_movements,'[]'::jsonb)) x
      union
      select distinct st.ingredient_id
      from public.stock_transactions st
      where st.reference_id = v_sale_id
        and st.transaction_type = 'SALE'
    )
  order by i.ingredient_id
  for update;

  -- Compute OLD sale movement totals before replacement.
  create temporary table if not exists _v190_old_sale_delta(
    ingredient_id uuid primary key,
    qty numeric not null
  ) on commit drop;
  truncate _v190_old_sale_delta;

  insert into _v190_old_sale_delta(ingredient_id, qty)
  select ingredient_id, sum(quantity)
  from public.stock_transactions
  where reference_id = v_sale_id
    and transaction_type = 'SALE'
  group by ingredient_id;

  -- Upsert sale.
  insert into public.sales(
    id,
    warehouse_id,
    total_amount,
    source,
    sold_at,
    note
  )
  values(
    v_sale_id,
    v_warehouse_id,
    coalesce((p_sale->>'total_amount')::numeric,0),
    coalesce(p_sale->>'source','manual'),
    coalesce((p_sale->>'sold_at')::timestamptz, now()),
    coalesce(p_sale->>'note','')
  )
  on conflict (id) do update
  set
    warehouse_id = excluded.warehouse_id,
    total_amount = excluded.total_amount,
    source = excluded.source,
    sold_at = excluded.sold_at,
    note = excluded.note;

  -- Replace sale items atomically.
  delete from public.sale_items
  where sale_id = v_sale_id;

  insert into public.sale_items(
    sale_id,
    product_id,
    quantity,
    unit_price
  )
  select
    v_sale_id,
    (x->>'product_id')::uuid,
    coalesce((x->>'quantity')::numeric,0),
    coalesce((x->>'unit_price')::numeric,0)
  from jsonb_array_elements(
    coalesce(p_sale_items,'[]'::jsonb)
  ) x;

  -- Replace SALE stock ledger rows atomically.
  delete from public.stock_transactions
  where reference_id = v_sale_id
    and transaction_type = 'SALE';

  insert into public.stock_transactions(
    warehouse_id,
    ingredient_id,
    transaction_type,
    quantity,
    note,
    reference_id
  )
  select
    v_warehouse_id,
    (x->>'ingredient_id')::uuid,
    'SALE',
    coalesce((x->>'quantity')::numeric,0),
    coalesce(x->>'note',''),
    v_sale_id
  from jsonb_array_elements(
    coalesce(p_stock_movements,'[]'::jsonb)
  ) x;

  -- NEW minus OLD movement = only delta that should touch inventory.
  create temporary table if not exists _v190_new_sale_delta(
    ingredient_id uuid primary key,
    qty numeric not null
  ) on commit drop;
  truncate _v190_new_sale_delta;

  insert into _v190_new_sale_delta(ingredient_id, qty)
  select
    (x->>'ingredient_id')::uuid,
    sum(
      coalesce(
        (x->>'quantity')::numeric,
        0
      )
    )
  from jsonb_array_elements(
    coalesce(p_stock_movements,'[]'::jsonb)
  ) x
  group by (x->>'ingredient_id')::uuid;

  -- Apply union of old/new ingredients.
  for v_new in
    select ingredient_id
    from (
      select ingredient_id from _v190_old_sale_delta
      union
      select ingredient_id from _v190_new_sale_delta
    ) u
    order by ingredient_id
  loop
    select coalesce(qty,0)
    into v_delta
    from _v190_new_sale_delta
    where ingredient_id = v_new.ingredient_id;

    v_delta := coalesce(v_delta,0);

    select coalesce(
      (
        select qty
        from _v190_old_sale_delta
        where ingredient_id = v_new.ingredient_id
      ),
      0
    )
    into v_old_qty;

    v_delta :=
      v_delta -
      coalesce(v_old_qty,0);

    insert into public.inventory(
      warehouse_id,
      ingredient_id,
      quantity,
      updated_at
    )
    values(
      v_warehouse_id,
      v_new.ingredient_id,
      v_delta,
      now()
    )
    on conflict (warehouse_id,ingredient_id)
    do update
    set
      quantity =
        public.inventory.quantity +
        excluded.quantity,
      updated_at = now();
  end loop;

  select to_jsonb(s)
  into v_sale_row
  from public.sales s
  where s.id = v_sale_id;

  select coalesce(jsonb_agg(to_jsonb(si) order by si.created_at, si.id),'[]'::jsonb)
  into v_items
  from public.sale_items si
  where si.sale_id = v_sale_id;

  select coalesce(jsonb_agg(to_jsonb(st) order by st.created_at, st.id),'[]'::jsonb)
  into v_movements
  from public.stock_transactions st
  where st.reference_id = v_sale_id
    and st.transaction_type = 'SALE';

  select coalesce(jsonb_agg(to_jsonb(i) order by i.ingredient_id),'[]'::jsonb)
  into v_inventory
  from public.inventory i
  where i.warehouse_id = v_warehouse_id
    and i.ingredient_id in (
      select ingredient_id from _v190_old_sale_delta
      union
      select ingredient_id from _v190_new_sale_delta
    );

  insert into public.app_operation_log(
    idempotency_key,
    operation_type,
    reference_id,
    result
  )
  values(
    p_idempotency_key,
    'SALE',
    v_sale_id,
    '{}'::jsonb
  )
  on conflict (idempotency_key)
  do update set
    operation_type = excluded.operation_type,
    reference_id = excluded.reference_id
  returning operation_revision
  into v_operation_revision;

  v_result :=
    jsonb_build_object(
      'sale',v_sale_row,
      'sale_items',v_items,
      'stock_transactions',v_movements,
      'inventory',v_inventory,
      'operation_revision',v_operation_revision,
      'payload_hash',
        encode(digest(
          coalesce(p_sale::text,'') ||
          coalesce(p_sale_items::text,'') ||
          coalesce(p_stock_movements::text,''),
          'sha256'
        ), 'hex')
    );

  update public.app_operation_log
  set result = v_result
  where idempotency_key = p_idempotency_key;

  return v_result - 'payload_hash';
end;
$$;

grant execute on function public.commit_sale_receipt_v190(jsonb,jsonb,jsonb,text)
to anon, authenticated;
