-- V192 - Atomic Export + Atomic Stocktake
-- Chạy SAU V189, V190, V191.

create extension if not exists pgcrypto;

alter table public.stock_transactions
  add column if not exists unit_cost numeric;
alter table public.stock_transactions
  add column if not exists total_cost numeric;
alter table public.stock_transactions
  add column if not exists supplier_id uuid;

create table if not exists public.app_operation_log (
  idempotency_key text primary key,
  operation_type text not null,
  reference_id uuid,
  operation_revision bigint generated by default as identity,
  result jsonb,
  created_at timestamptz not null default now()
);

-- EXPORT create/edit atomically. Quantity in movements is negative.
create or replace function public.commit_export_receipt_v192(
  p_reference_id uuid,
  p_old_reference_id uuid,
  p_warehouse_id uuid,
  p_movements jsonb,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_existing jsonb;
  v_payload_hash text;
  v_result jsonb;
  v_movements jsonb;
  v_inventory jsonb;
  v_rev bigint;
  v_item record;
  v_old_ref uuid;
begin
  v_old_ref:=coalesce(p_old_reference_id,p_reference_id);

  v_payload_hash:=encode(digest(
    coalesce(p_reference_id::text,'')||
    coalesce(p_old_reference_id::text,'')||
    coalesce(p_warehouse_id::text,'')||
    coalesce(p_movements::text,''),'sha256'),'hex');

  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key,0));

  select result into v_existing
  from public.app_operation_log
  where idempotency_key=p_idempotency_key;

  if v_existing is not null
     and coalesce(v_existing->>'payload_hash','')=v_payload_hash then
    return v_existing-'payload_hash';
  end if;

  -- Ensure/lock rows in deterministic order.
  insert into public.inventory(warehouse_id,ingredient_id,quantity,updated_at)
  select p_warehouse_id,(x->>'ingredient_id')::uuid,0,now()
  from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
  on conflict (warehouse_id,ingredient_id) do nothing;

  perform 1 from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct ingredient_id from public.stock_transactions
      where reference_id=v_old_ref and transaction_type='EXPORT'
      union
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
    )
  order by i.ingredient_id
  for update;

  create temporary table if not exists _v192_export_old(
    ingredient_id uuid primary key, qty numeric not null
  ) on commit drop;
  truncate _v192_export_old;

  insert into _v192_export_old
  select ingredient_id,sum(quantity)
  from public.stock_transactions
  where reference_id=v_old_ref and transaction_type='EXPORT'
  group by ingredient_id;

  -- Reverse old export effect.
  for v_item in select * from _v192_export_old order by ingredient_id loop
    update public.inventory
    set quantity=quantity-coalesce(v_item.qty,0),updated_at=now()
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id;
  end loop;

  delete from public.stock_transactions
  where transaction_type='EXPORT'
    and reference_id in (v_old_ref,p_reference_id);

  insert into public.stock_transactions(
    warehouse_id,ingredient_id,transaction_type,quantity,note,reference_id,
    unit_cost,total_cost
  )
  select
    p_warehouse_id,
    (x->>'ingredient_id')::uuid,
    'EXPORT',
    coalesce((x->>'quantity')::numeric,0),
    coalesce(x->>'note',''),
    p_reference_id,
    coalesce((x->>'unit_cost')::numeric,0),
    coalesce((x->>'total_cost')::numeric,0)
  from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x;

  -- Apply new export effect.
  for v_item in
    select (x->>'ingredient_id')::uuid ingredient_id,
           sum(coalesce((x->>'quantity')::numeric,0)) qty
    from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
    group by (x->>'ingredient_id')::uuid
    order by ingredient_id
  loop
    update public.inventory
    set quantity=quantity+coalesce(v_item.qty,0),updated_at=now()
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id;
  end loop;

  select coalesce(jsonb_agg(to_jsonb(st) order by st.created_at,st.id),'[]'::jsonb)
  into v_movements
  from public.stock_transactions st
  where st.reference_id=p_reference_id and st.transaction_type='EXPORT';

  select coalesce(jsonb_agg(to_jsonb(i) order by i.ingredient_id),'[]'::jsonb)
  into v_inventory
  from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
    );

  insert into public.app_operation_log(idempotency_key,operation_type,reference_id,result)
  values(p_idempotency_key,'EXPORT',p_reference_id,'{}'::jsonb)
  on conflict(idempotency_key) do update set
    operation_type=excluded.operation_type,reference_id=excluded.reference_id
  returning operation_revision into v_rev;

  v_result:=jsonb_build_object(
    'stock_transactions',v_movements,'inventory',v_inventory,
    'operation_revision',v_rev,'payload_hash',v_payload_hash
  );
  update public.app_operation_log set result=v_result
  where idempotency_key=p_idempotency_key;

  return v_result-'payload_hash';
end;
$$;

create or replace function public.delete_export_receipt_v192(
  p_reference_id uuid,
  p_warehouse_id uuid
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare v_item record;
begin
  perform pg_advisory_xact_lock(hashtextextended('export:'||p_reference_id::text,0));

  for v_item in
    select ingredient_id,sum(quantity) qty
    from public.stock_transactions
    where reference_id=p_reference_id and transaction_type='EXPORT'
    group by ingredient_id
    order by ingredient_id
  loop
    insert into public.inventory(warehouse_id,ingredient_id,quantity,updated_at)
    values(p_warehouse_id,v_item.ingredient_id,-coalesce(v_item.qty,0),now())
    on conflict(warehouse_id,ingredient_id) do update set
      quantity=public.inventory.quantity+excluded.quantity,updated_at=now();
  end loop;

  delete from public.stock_transactions
  where reference_id=p_reference_id and transaction_type='EXPORT';
  return true;
end;
$$;

-- STOCKTAKE: actual quantity is authoritative at the transaction order point.
create or replace function public.commit_stocktake_receipt_v192(
  p_reference_id uuid,
  p_old_reference_id uuid,
  p_warehouse_id uuid,
  p_lines jsonb,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_existing jsonb;
  v_payload_hash text;
  v_result jsonb;
  v_movements jsonb;
  v_inventory jsonb;
  v_rev bigint;
  v_item record;
  v_old_ref uuid;
  v_current numeric;
  v_actual numeric;
  v_diff numeric;
begin
  v_old_ref:=coalesce(p_old_reference_id,p_reference_id);
  v_payload_hash:=encode(digest(
    coalesce(p_reference_id::text,'')||
    coalesce(p_old_reference_id::text,'')||
    coalesce(p_warehouse_id::text,'')||
    coalesce(p_lines::text,''),'sha256'),'hex');

  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key,0));

  select result into v_existing from public.app_operation_log
  where idempotency_key=p_idempotency_key;
  if v_existing is not null
     and coalesce(v_existing->>'payload_hash','')=v_payload_hash then
    return v_existing-'payload_hash';
  end if;

  insert into public.inventory(warehouse_id,ingredient_id,quantity,updated_at)
  select p_warehouse_id,(x->>'ingredient_id')::uuid,0,now()
  from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) x
  on conflict(warehouse_id,ingredient_id) do nothing;

  perform 1 from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct ingredient_id from public.stock_transactions
      where reference_id=v_old_ref and transaction_type='ADJUSTMENT'
      union
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) x
    )
  order by i.ingredient_id
  for update;

  -- Editing/retry: remove previous receipt effect first.
  for v_item in
    select ingredient_id,sum(quantity) qty
    from public.stock_transactions
    where reference_id=v_old_ref and transaction_type='ADJUSTMENT'
    group by ingredient_id
    order by ingredient_id
  loop
    update public.inventory
    set quantity=quantity-coalesce(v_item.qty,0),updated_at=now()
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id;
  end loop;

  delete from public.stock_transactions
  where transaction_type='ADJUSTMENT'
    and reference_id in (v_old_ref,p_reference_id);

  -- Apply physical count sequentially under row locks.
  for v_item in
    select
      (x->>'ingredient_id')::uuid ingredient_id,
      coalesce((x->>'actual')::numeric,0) actual,
      coalesce(x->>'note','') note
    from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) x
    order by (x->>'ingredient_id')::uuid
  loop
    select quantity into v_current
    from public.inventory
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id
    for update;

    v_actual:=v_item.actual;
    v_diff:=v_actual-coalesce(v_current,0);

    update public.inventory
    set quantity=v_actual,updated_at=now()
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id;

    if abs(v_diff)>0.000001 then
      insert into public.stock_transactions(
        warehouse_id,ingredient_id,transaction_type,quantity,note,reference_id
      )
      values(
        p_warehouse_id,v_item.ingredient_id,'ADJUSTMENT',
        v_diff,v_item.note,p_reference_id
      );
    end if;
  end loop;

  select coalesce(jsonb_agg(to_jsonb(st) order by st.created_at,st.id),'[]'::jsonb)
  into v_movements
  from public.stock_transactions st
  where st.reference_id=p_reference_id and st.transaction_type='ADJUSTMENT';

  select coalesce(jsonb_agg(to_jsonb(i) order by i.ingredient_id),'[]'::jsonb)
  into v_inventory
  from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) x
    );

  insert into public.app_operation_log(idempotency_key,operation_type,reference_id,result)
  values(p_idempotency_key,'STOCKTAKE',p_reference_id,'{}'::jsonb)
  on conflict(idempotency_key) do update set
    operation_type=excluded.operation_type,reference_id=excluded.reference_id
  returning operation_revision into v_rev;

  v_result:=jsonb_build_object(
    'stock_transactions',v_movements,'inventory',v_inventory,
    'operation_revision',v_rev,'payload_hash',v_payload_hash
  );
  update public.app_operation_log set result=v_result
  where idempotency_key=p_idempotency_key;

  return v_result-'payload_hash';
end;
$$;

create or replace function public.delete_stocktake_receipt_v192(
  p_reference_id uuid,
  p_warehouse_id uuid
)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare v_item record;
begin
  perform pg_advisory_xact_lock(hashtextextended('stocktake:'||p_reference_id::text,0));

  for v_item in
    select ingredient_id,sum(quantity) qty
    from public.stock_transactions
    where reference_id=p_reference_id and transaction_type='ADJUSTMENT'
    group by ingredient_id
    order by ingredient_id
  loop
    insert into public.inventory(warehouse_id,ingredient_id,quantity,updated_at)
    values(p_warehouse_id,v_item.ingredient_id,-coalesce(v_item.qty,0),now())
    on conflict(warehouse_id,ingredient_id) do update set
      quantity=public.inventory.quantity+excluded.quantity,updated_at=now();
  end loop;

  delete from public.stock_transactions
  where reference_id=p_reference_id and transaction_type='ADJUSTMENT';

  return true;
end;
$$;

grant execute on function public.commit_export_receipt_v192(uuid,uuid,uuid,jsonb,text)
to anon,authenticated;
grant execute on function public.delete_export_receipt_v192(uuid,uuid)
to anon,authenticated;
grant execute on function public.commit_stocktake_receipt_v192(uuid,uuid,uuid,jsonb,text)
to anon,authenticated;
grant execute on function public.delete_stocktake_receipt_v192(uuid,uuid)
to anon,authenticated;
