-- ============================================================
-- QUẢN LÝ LÁT YÊN - SUPABASE FULL SYNC UPDATE
-- Compatible with app V192
-- Includes: V189 + V190 + V191 + V192
-- Generated: 2026-08-22
--
-- HOW TO USE
-- 1) Supabase -> SQL Editor -> New query
-- 2) Paste/run this entire file once
-- 3) Deploy app V192 on all devices
-- 4) Reload app and press "Đồng bộ ngay"
--
-- This script is designed to be re-runnable:
-- - CREATE TABLE IF NOT EXISTS
-- - ADD COLUMN IF NOT EXISTS
-- - CREATE OR REPLACE FUNCTION
-- - DROP POLICY IF EXISTS before CREATE POLICY where needed
-- ============================================================

BEGIN;


-- ============================================================
-- SECTION 1: SUPABASE-V189-TRANSACTIONAL-SYNC.sql
-- ============================================================

-- V189 - Transactional canonical sync
-- Chạy 1 lần trong Supabase > SQL Editor.

create table if not exists public.app_sync_state (
  sync_key text primary key,
  revision bigint not null default 0,
  envelope jsonb,
  updated_at timestamptz not null default now()
);

alter table public.app_sync_state enable row level security;

drop policy if exists "app_sync_state_select" on public.app_sync_state;
create policy "app_sync_state_select"
on public.app_sync_state
for select
to anon, authenticated
using (true);

drop policy if exists "app_sync_state_insert" on public.app_sync_state;
create policy "app_sync_state_insert"
on public.app_sync_state
for insert
to anon, authenticated
with check (true);

drop policy if exists "app_sync_state_update" on public.app_sync_state;
create policy "app_sync_state_update"
on public.app_sync_state
for update
to anon, authenticated
using (true)
with check (true);

create or replace function public.commit_app_sync_state(
  p_sync_key text,
  p_expected_revision bigint,
  p_envelope jsonb
)
returns table (
  success boolean,
  revision bigint,
  envelope jsonb,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_row public.app_sync_state%rowtype;
begin
  insert into public.app_sync_state(sync_key, revision, envelope)
  values (p_sync_key, 0, null)
  on conflict (sync_key) do nothing;

  update public.app_sync_state
  set
    revision = app_sync_state.revision + 1,
    envelope = p_envelope,
    updated_at = now()
  where
    sync_key = p_sync_key
    and app_sync_state.revision = p_expected_revision
  returning * into v_row;

  if found then
    return query
    select
      true,
      v_row.revision,
      v_row.envelope,
      v_row.updated_at;
    return;
  end if;

  select *
  into v_row
  from public.app_sync_state
  where sync_key = p_sync_key;

  return query
  select
    false,
    coalesce(v_row.revision, 0),
    v_row.envelope,
    v_row.updated_at;
end;
$$;

grant execute on function public.commit_app_sync_state(text,bigint,jsonb)
to anon, authenticated;

grant select, insert, update on public.app_sync_state
to anon, authenticated;

-- ============================================================
-- SECTION 2: SUPABASE-V190-ATOMIC-SALES.sql
-- ============================================================

-- V190 - Atomic sales + inventory
create extension if not exists pgcrypto with schema extensions;

alter table public.sales add column if not exists note text;

-- Chạy 1 lần trong Supabase > SQL Editor.
-- Yêu cầu các bảng hiện có: sales, sale_items, stock_transactions, inventory.

create table if not exists public.app_operation_log (
  idempotency_key text primary key,
  operation_type text not null,
  reference_id uuid,
  operation_revision bigint generated by default as identity,
  result jsonb,
  created_at timestamptz not null default now()
);

alter table public.app_operation_log enable row level security;

drop policy if exists "app_operation_log_select" on public.app_operation_log;
create policy "app_operation_log_select"
on public.app_operation_log
for select
to anon, authenticated
using (true);

grant select on public.app_operation_log to anon, authenticated;

create or replace function public.commit_sale_receipt_v190(
  p_sale jsonb,
  p_sale_items jsonb,
  p_stock_movements jsonb,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_sale_id uuid;
  v_warehouse_id uuid;
  v_existing jsonb;
  v_old_qty numeric;
  v_new record;
  v_delta numeric;
  v_result jsonb;
  v_sale_row jsonb;
  v_items jsonb;
  v_movements jsonb;
  v_inventory jsonb;
  v_operation_revision bigint;
begin
  if p_idempotency_key is null or length(trim(p_idempotency_key)) < 6 then
    raise exception 'Invalid idempotency key';
  end if;

  v_sale_id := (p_sale->>'id')::uuid;
  v_warehouse_id := (p_sale->>'warehouse_id')::uuid;

  -- Serialize all retries / concurrent commits for the same sale.
  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key, 0));

  select result
  into v_existing
  from public.app_operation_log
  where idempotency_key = p_idempotency_key;

  -- For CREATE retry, return same committed result.
  -- For EDIT we allow recomputation when payload changed; operation log is replaced below.
  if v_existing is not null
     and coalesce(v_existing->>'payload_hash','') =
         encode(digest(
           coalesce(p_sale::text,'') ||
           coalesce(p_sale_items::text,'') ||
           coalesce(p_stock_movements::text,''),
           'sha256'
         ), 'hex')
  then
    return v_existing - 'payload_hash';
  end if;

  -- Lock affected inventory rows deterministically to avoid deadlocks.
  perform 1
  from public.inventory i
  where i.warehouse_id = v_warehouse_id
    and i.ingredient_id in (
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_stock_movements,'[]'::jsonb)) x
      union
      select distinct st.ingredient_id
      from public.stock_transactions st
      where st.reference_id = v_sale_id
        and st.transaction_type = 'SALE'
    )
  order by i.ingredient_id
  for update;

  -- Compute OLD sale movement totals before replacement.
  create temporary table if not exists _v190_old_sale_delta(
    ingredient_id uuid primary key,
    qty numeric not null
  ) on commit drop;
  truncate _v190_old_sale_delta;

  insert into _v190_old_sale_delta(ingredient_id, qty)
  select ingredient_id, sum(quantity)
  from public.stock_transactions
  where reference_id = v_sale_id
    and transaction_type = 'SALE'
  group by ingredient_id;

  -- Upsert sale.
  insert into public.sales(
    id,
    warehouse_id,
    total_amount,
    source,
    sold_at,
    note
  )
  values(
    v_sale_id,
    v_warehouse_id,
    coalesce((p_sale->>'total_amount')::numeric,0),
    coalesce(p_sale->>'source','manual'),
    coalesce((p_sale->>'sold_at')::timestamptz, now()),
    coalesce(p_sale->>'note','')
  )
  on conflict (id) do update
  set
    warehouse_id = excluded.warehouse_id,
    total_amount = excluded.total_amount,
    source = excluded.source,
    sold_at = excluded.sold_at,
    note = excluded.note;

  -- Replace sale items atomically.
  delete from public.sale_items
  where sale_id = v_sale_id;

  insert into public.sale_items(
    sale_id,
    product_id,
    quantity,
    unit_price
  )
  select
    v_sale_id,
    (x->>'product_id')::uuid,
    coalesce((x->>'quantity')::numeric,0),
    coalesce((x->>'unit_price')::numeric,0)
  from jsonb_array_elements(
    coalesce(p_sale_items,'[]'::jsonb)
  ) x;

  -- Replace SALE stock ledger rows atomically.
  delete from public.stock_transactions
  where reference_id = v_sale_id
    and transaction_type = 'SALE';

  insert into public.stock_transactions(
    warehouse_id,
    ingredient_id,
    transaction_type,
    quantity,
    note,
    reference_id
  )
  select
    v_warehouse_id,
    (x->>'ingredient_id')::uuid,
    'SALE',
    coalesce((x->>'quantity')::numeric,0),
    coalesce(x->>'note',''),
    v_sale_id
  from jsonb_array_elements(
    coalesce(p_stock_movements,'[]'::jsonb)
  ) x;

  -- NEW minus OLD movement = only delta that should touch inventory.
  create temporary table if not exists _v190_new_sale_delta(
    ingredient_id uuid primary key,
    qty numeric not null
  ) on commit drop;
  truncate _v190_new_sale_delta;

  insert into _v190_new_sale_delta(ingredient_id, qty)
  select
    (x->>'ingredient_id')::uuid,
    sum(
      coalesce(
        (x->>'quantity')::numeric,
        0
      )
    )
  from jsonb_array_elements(
    coalesce(p_stock_movements,'[]'::jsonb)
  ) x
  group by (x->>'ingredient_id')::uuid;

  -- Apply union of old/new ingredients.
  for v_new in
    select ingredient_id
    from (
      select ingredient_id from _v190_old_sale_delta
      union
      select ingredient_id from _v190_new_sale_delta
    ) u
    order by ingredient_id
  loop
    select coalesce(qty,0)
    into v_delta
    from _v190_new_sale_delta
    where ingredient_id = v_new.ingredient_id;

    v_delta := coalesce(v_delta,0);

    select coalesce(
      (
        select qty
        from _v190_old_sale_delta
        where ingredient_id = v_new.ingredient_id
      ),
      0
    )
    into v_old_qty;

    v_delta :=
      v_delta -
      coalesce(v_old_qty,0);

    insert into public.inventory(
      warehouse_id,
      ingredient_id,
      quantity,
      updated_at
    )
    values(
      v_warehouse_id,
      v_new.ingredient_id,
      v_delta,
      now()
    )
    on conflict (warehouse_id,ingredient_id)
    do update
    set
      quantity =
        public.inventory.quantity +
        excluded.quantity,
      updated_at = now();
  end loop;

  select to_jsonb(s)
  into v_sale_row
  from public.sales s
  where s.id = v_sale_id;

  select coalesce(jsonb_agg(to_jsonb(si) order by si.created_at, si.id),'[]'::jsonb)
  into v_items
  from public.sale_items si
  where si.sale_id = v_sale_id;

  select coalesce(jsonb_agg(to_jsonb(st) order by st.created_at, st.id),'[]'::jsonb)
  into v_movements
  from public.stock_transactions st
  where st.reference_id = v_sale_id
    and st.transaction_type = 'SALE';

  select coalesce(jsonb_agg(to_jsonb(i) order by i.ingredient_id),'[]'::jsonb)
  into v_inventory
  from public.inventory i
  where i.warehouse_id = v_warehouse_id
    and i.ingredient_id in (
      select ingredient_id from _v190_old_sale_delta
      union
      select ingredient_id from _v190_new_sale_delta
    );

  insert into public.app_operation_log(
    idempotency_key,
    operation_type,
    reference_id,
    result
  )
  values(
    p_idempotency_key,
    'SALE',
    v_sale_id,
    '{}'::jsonb
  )
  on conflict (idempotency_key)
  do update set
    operation_type = excluded.operation_type,
    reference_id = excluded.reference_id
  returning operation_revision
  into v_operation_revision;

  v_result :=
    jsonb_build_object(
      'sale',v_sale_row,
      'sale_items',v_items,
      'stock_transactions',v_movements,
      'inventory',v_inventory,
      'operation_revision',v_operation_revision,
      'payload_hash',
        encode(digest(
          coalesce(p_sale::text,'') ||
          coalesce(p_sale_items::text,'') ||
          coalesce(p_stock_movements::text,''),
          'sha256'
        ), 'hex')
    );

  update public.app_operation_log
  set result = v_result
  where idempotency_key = p_idempotency_key;

  return v_result - 'payload_hash';
end;
$$;

grant execute on function public.commit_sale_receipt_v190(jsonb,jsonb,jsonb,text)
to anon, authenticated;

-- ============================================================
-- SECTION 3: SUPABASE-V191-ATOMIC-IMPORT.sql
-- ============================================================

-- V191 - Atomic Import + reliable retry
-- Chạy SAU SQL V189 và V190.

create extension if not exists pgcrypto with schema extensions;

create or replace function public.commit_import_receipt_v191(
  p_reference_id uuid,
  p_warehouse_id uuid,
  p_movements jsonb,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_existing jsonb;
  v_payload_hash text;
  v_result jsonb;
  v_movements jsonb;
  v_inventory jsonb;
  v_operation_revision bigint;
  v_item record;
begin
  if p_idempotency_key is null or length(trim(p_idempotency_key)) < 6 then
    raise exception 'Invalid idempotency key';
  end if;

  v_payload_hash :=
    encode(
      digest(
        coalesce(p_reference_id::text,'') ||
        coalesce(p_warehouse_id::text,'') ||
        coalesce(p_movements::text,''),
        'sha256'
      ),
      'hex'
    );

  perform pg_advisory_xact_lock(
    hashtextextended(p_idempotency_key,0)
  );

  select result
  into v_existing
  from public.app_operation_log
  where idempotency_key=p_idempotency_key;

  if v_existing is not null
     and coalesce(v_existing->>'payload_hash','')=v_payload_hash
  then
    return v_existing - 'payload_hash';
  end if;

  -- Lock every affected inventory row in deterministic order.
  perform 1
  from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
    )
  order by i.ingredient_id
  for update;

  -- If this reference already exists, remove its previous inventory effect first.
  for v_item in
    select ingredient_id,sum(quantity) as qty
    from public.stock_transactions
    where reference_id=p_reference_id
      and transaction_type='IMPORT'
    group by ingredient_id
    order by ingredient_id
  loop
    insert into public.inventory(
      warehouse_id,ingredient_id,quantity,updated_at
    )
    values(
      p_warehouse_id,
      v_item.ingredient_id,
      -coalesce(v_item.qty,0),
      now()
    )
    on conflict (warehouse_id,ingredient_id)
    do update set
      quantity=public.inventory.quantity + excluded.quantity,
      updated_at=now();
  end loop;

  delete from public.stock_transactions
  where reference_id=p_reference_id
    and transaction_type='IMPORT';

  insert into public.stock_transactions(
    warehouse_id,
    ingredient_id,
    transaction_type,
    quantity,
    note,
    reference_id,
    unit_cost,
    total_cost,
    supplier_id
  )
  select
    p_warehouse_id,
    (x->>'ingredient_id')::uuid,
    'IMPORT',
    coalesce((x->>'quantity')::numeric,0),
    coalesce(x->>'note',''),
    p_reference_id,
    coalesce((x->>'unit_cost')::numeric,0),
    coalesce((x->>'total_cost')::numeric,0),
    case
      when nullif(x->>'supplier_id','') is null then null
      else (x->>'supplier_id')::uuid
    end
  from jsonb_array_elements(
    coalesce(p_movements,'[]'::jsonb)
  ) x;

  -- Apply the complete new import effect atomically.
  for v_item in
    select
      (x->>'ingredient_id')::uuid as ingredient_id,
      sum(coalesce((x->>'quantity')::numeric,0)) as qty
    from jsonb_array_elements(
      coalesce(p_movements,'[]'::jsonb)
    ) x
    group by (x->>'ingredient_id')::uuid
    order by ingredient_id
  loop
    insert into public.inventory(
      warehouse_id,ingredient_id,quantity,updated_at
    )
    values(
      p_warehouse_id,
      v_item.ingredient_id,
      coalesce(v_item.qty,0),
      now()
    )
    on conflict (warehouse_id,ingredient_id)
    do update set
      quantity=public.inventory.quantity + excluded.quantity,
      updated_at=now();
  end loop;

  -- Update ingredient cost using latest movement unit_cost when available.
  for v_item in
    select
      (x->>'ingredient_id')::uuid as ingredient_id,
      max(coalesce((x->>'unit_cost')::numeric,0)) as unit_cost
    from jsonb_array_elements(
      coalesce(p_movements,'[]'::jsonb)
    ) x
    group by (x->>'ingredient_id')::uuid
  loop
    if v_item.unit_cost >= 0 then
      update public.ingredients
      set
        cost=v_item.unit_cost,
        updated_at=now()
      where id=v_item.ingredient_id;
    end if;
  end loop;

  select coalesce(
    jsonb_agg(to_jsonb(st) order by st.created_at,st.id),
    '[]'::jsonb
  )
  into v_movements
  from public.stock_transactions st
  where st.reference_id=p_reference_id
    and st.transaction_type='IMPORT';

  select coalesce(
    jsonb_agg(to_jsonb(i) order by i.ingredient_id),
    '[]'::jsonb
  )
  into v_inventory
  from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
    );

  insert into public.app_operation_log(
    idempotency_key,
    operation_type,
    reference_id,
    result
  )
  values(
    p_idempotency_key,
    'IMPORT',
    p_reference_id,
    '{}'::jsonb
  )
  on conflict (idempotency_key)
  do update set
    operation_type=excluded.operation_type,
    reference_id=excluded.reference_id
  returning operation_revision
  into v_operation_revision;

  v_result :=
    jsonb_build_object(
      'stock_transactions',v_movements,
      'inventory',v_inventory,
      'operation_revision',v_operation_revision,
      'payload_hash',v_payload_hash
    );

  update public.app_operation_log
  set result=v_result
  where idempotency_key=p_idempotency_key;

  return v_result - 'payload_hash';
end;
$$;

grant execute on function public.commit_import_receipt_v191(uuid,uuid,jsonb,text)
to anon, authenticated;

-- ============================================================
-- SECTION 4: SUPABASE-V192-FULL-MENU-SYNC.sql
-- ============================================================

-- V192 - Atomic Export + Atomic Stocktake
-- Chạy SAU V189, V190, V191.

create extension if not exists pgcrypto with schema extensions;

alter table public.stock_transactions
  add column if not exists unit_cost numeric;
alter table public.stock_transactions
  add column if not exists total_cost numeric;
alter table public.stock_transactions
  add column if not exists supplier_id uuid;

create table if not exists public.app_operation_log (
  idempotency_key text primary key,
  operation_type text not null,
  reference_id uuid,
  operation_revision bigint generated by default as identity,
  result jsonb,
  created_at timestamptz not null default now()
);

-- EXPORT create/edit atomically. Quantity in movements is negative.
create or replace function public.commit_export_receipt_v192(
  p_reference_id uuid,
  p_old_reference_id uuid,
  p_warehouse_id uuid,
  p_movements jsonb,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path=public, extensions
as $$
declare
  v_existing jsonb;
  v_payload_hash text;
  v_result jsonb;
  v_movements jsonb;
  v_inventory jsonb;
  v_rev bigint;
  v_item record;
  v_old_ref uuid;
begin
  v_old_ref:=coalesce(p_old_reference_id,p_reference_id);

  v_payload_hash:=encode(digest(
    coalesce(p_reference_id::text,'')||
    coalesce(p_old_reference_id::text,'')||
    coalesce(p_warehouse_id::text,'')||
    coalesce(p_movements::text,''),'sha256'),'hex');

  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key,0));

  select result into v_existing
  from public.app_operation_log
  where idempotency_key=p_idempotency_key;

  if v_existing is not null
     and coalesce(v_existing->>'payload_hash','')=v_payload_hash then
    return v_existing-'payload_hash';
  end if;

  -- Ensure/lock rows in deterministic order.
  insert into public.inventory(warehouse_id,ingredient_id,quantity,updated_at)
  select p_warehouse_id,(x->>'ingredient_id')::uuid,0,now()
  from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
  on conflict (warehouse_id,ingredient_id) do nothing;

  perform 1 from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct ingredient_id from public.stock_transactions
      where reference_id=v_old_ref and transaction_type='EXPORT'
      union
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
    )
  order by i.ingredient_id
  for update;

  create temporary table if not exists _v192_export_old(
    ingredient_id uuid primary key, qty numeric not null
  ) on commit drop;
  truncate _v192_export_old;

  insert into _v192_export_old
  select ingredient_id,sum(quantity)
  from public.stock_transactions
  where reference_id=v_old_ref and transaction_type='EXPORT'
  group by ingredient_id;

  -- Reverse old export effect.
  for v_item in select * from _v192_export_old order by ingredient_id loop
    update public.inventory
    set quantity=quantity-coalesce(v_item.qty,0),updated_at=now()
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id;
  end loop;

  delete from public.stock_transactions
  where transaction_type='EXPORT'
    and reference_id in (v_old_ref,p_reference_id);

  insert into public.stock_transactions(
    warehouse_id,ingredient_id,transaction_type,quantity,note,reference_id,
    unit_cost,total_cost
  )
  select
    p_warehouse_id,
    (x->>'ingredient_id')::uuid,
    'EXPORT',
    coalesce((x->>'quantity')::numeric,0),
    coalesce(x->>'note',''),
    p_reference_id,
    coalesce((x->>'unit_cost')::numeric,0),
    coalesce((x->>'total_cost')::numeric,0)
  from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x;

  -- Apply new export effect.
  for v_item in
    select (x->>'ingredient_id')::uuid ingredient_id,
           sum(coalesce((x->>'quantity')::numeric,0)) qty
    from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
    group by (x->>'ingredient_id')::uuid
    order by ingredient_id
  loop
    update public.inventory
    set quantity=quantity+coalesce(v_item.qty,0),updated_at=now()
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id;
  end loop;

  select coalesce(jsonb_agg(to_jsonb(st) order by st.created_at,st.id),'[]'::jsonb)
  into v_movements
  from public.stock_transactions st
  where st.reference_id=p_reference_id and st.transaction_type='EXPORT';

  select coalesce(jsonb_agg(to_jsonb(i) order by i.ingredient_id),'[]'::jsonb)
  into v_inventory
  from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_movements,'[]'::jsonb)) x
    );

  insert into public.app_operation_log(idempotency_key,operation_type,reference_id,result)
  values(p_idempotency_key,'EXPORT',p_reference_id,'{}'::jsonb)
  on conflict(idempotency_key) do update set
    operation_type=excluded.operation_type,reference_id=excluded.reference_id
  returning operation_revision into v_rev;

  v_result:=jsonb_build_object(
    'stock_transactions',v_movements,'inventory',v_inventory,
    'operation_revision',v_rev,'payload_hash',v_payload_hash
  );
  update public.app_operation_log set result=v_result
  where idempotency_key=p_idempotency_key;

  return v_result-'payload_hash';
end;
$$;

create or replace function public.delete_export_receipt_v192(
  p_reference_id uuid,
  p_warehouse_id uuid
)
returns boolean
language plpgsql
security definer
set search_path=public, extensions
as $$
declare v_item record;
begin
  perform pg_advisory_xact_lock(hashtextextended('export:'||p_reference_id::text,0));

  for v_item in
    select ingredient_id,sum(quantity) qty
    from public.stock_transactions
    where reference_id=p_reference_id and transaction_type='EXPORT'
    group by ingredient_id
    order by ingredient_id
  loop
    insert into public.inventory(warehouse_id,ingredient_id,quantity,updated_at)
    values(p_warehouse_id,v_item.ingredient_id,-coalesce(v_item.qty,0),now())
    on conflict(warehouse_id,ingredient_id) do update set
      quantity=public.inventory.quantity+excluded.quantity,updated_at=now();
  end loop;

  delete from public.stock_transactions
  where reference_id=p_reference_id and transaction_type='EXPORT';
  return true;
end;
$$;

-- STOCKTAKE: actual quantity is authoritative at the transaction order point.
create or replace function public.commit_stocktake_receipt_v192(
  p_reference_id uuid,
  p_old_reference_id uuid,
  p_warehouse_id uuid,
  p_lines jsonb,
  p_idempotency_key text
)
returns jsonb
language plpgsql
security definer
set search_path=public, extensions
as $$
declare
  v_existing jsonb;
  v_payload_hash text;
  v_result jsonb;
  v_movements jsonb;
  v_inventory jsonb;
  v_rev bigint;
  v_item record;
  v_old_ref uuid;
  v_current numeric;
  v_actual numeric;
  v_diff numeric;
begin
  v_old_ref:=coalesce(p_old_reference_id,p_reference_id);
  v_payload_hash:=encode(digest(
    coalesce(p_reference_id::text,'')||
    coalesce(p_old_reference_id::text,'')||
    coalesce(p_warehouse_id::text,'')||
    coalesce(p_lines::text,''),'sha256'),'hex');

  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key,0));

  select result into v_existing from public.app_operation_log
  where idempotency_key=p_idempotency_key;
  if v_existing is not null
     and coalesce(v_existing->>'payload_hash','')=v_payload_hash then
    return v_existing-'payload_hash';
  end if;

  insert into public.inventory(warehouse_id,ingredient_id,quantity,updated_at)
  select p_warehouse_id,(x->>'ingredient_id')::uuid,0,now()
  from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) x
  on conflict(warehouse_id,ingredient_id) do nothing;

  perform 1 from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct ingredient_id from public.stock_transactions
      where reference_id=v_old_ref and transaction_type='ADJUSTMENT'
      union
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) x
    )
  order by i.ingredient_id
  for update;

  -- Editing/retry: remove previous receipt effect first.
  for v_item in
    select ingredient_id,sum(quantity) qty
    from public.stock_transactions
    where reference_id=v_old_ref and transaction_type='ADJUSTMENT'
    group by ingredient_id
    order by ingredient_id
  loop
    update public.inventory
    set quantity=quantity-coalesce(v_item.qty,0),updated_at=now()
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id;
  end loop;

  delete from public.stock_transactions
  where transaction_type='ADJUSTMENT'
    and reference_id in (v_old_ref,p_reference_id);

  -- Apply physical count sequentially under row locks.
  for v_item in
    select
      (x->>'ingredient_id')::uuid ingredient_id,
      coalesce((x->>'actual')::numeric,0) actual,
      coalesce(x->>'note','') note
    from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) x
    order by (x->>'ingredient_id')::uuid
  loop
    select quantity into v_current
    from public.inventory
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id
    for update;

    v_actual:=v_item.actual;
    v_diff:=v_actual-coalesce(v_current,0);

    update public.inventory
    set quantity=v_actual,updated_at=now()
    where warehouse_id=p_warehouse_id and ingredient_id=v_item.ingredient_id;

    if abs(v_diff)>0.000001 then
      insert into public.stock_transactions(
        warehouse_id,ingredient_id,transaction_type,quantity,note,reference_id
      )
      values(
        p_warehouse_id,v_item.ingredient_id,'ADJUSTMENT',
        v_diff,v_item.note,p_reference_id
      );
    end if;
  end loop;

  select coalesce(jsonb_agg(to_jsonb(st) order by st.created_at,st.id),'[]'::jsonb)
  into v_movements
  from public.stock_transactions st
  where st.reference_id=p_reference_id and st.transaction_type='ADJUSTMENT';

  select coalesce(jsonb_agg(to_jsonb(i) order by i.ingredient_id),'[]'::jsonb)
  into v_inventory
  from public.inventory i
  where i.warehouse_id=p_warehouse_id
    and i.ingredient_id in (
      select distinct (x->>'ingredient_id')::uuid
      from jsonb_array_elements(coalesce(p_lines,'[]'::jsonb)) x
    );

  insert into public.app_operation_log(idempotency_key,operation_type,reference_id,result)
  values(p_idempotency_key,'STOCKTAKE',p_reference_id,'{}'::jsonb)
  on conflict(idempotency_key) do update set
    operation_type=excluded.operation_type,reference_id=excluded.reference_id
  returning operation_revision into v_rev;

  v_result:=jsonb_build_object(
    'stock_transactions',v_movements,'inventory',v_inventory,
    'operation_revision',v_rev,'payload_hash',v_payload_hash
  );
  update public.app_operation_log set result=v_result
  where idempotency_key=p_idempotency_key;

  return v_result-'payload_hash';
end;
$$;

create or replace function public.delete_stocktake_receipt_v192(
  p_reference_id uuid,
  p_warehouse_id uuid
)
returns boolean
language plpgsql
security definer
set search_path=public, extensions
as $$
declare v_item record;
begin
  perform pg_advisory_xact_lock(hashtextextended('stocktake:'||p_reference_id::text,0));

  for v_item in
    select ingredient_id,sum(quantity) qty
    from public.stock_transactions
    where reference_id=p_reference_id and transaction_type='ADJUSTMENT'
    group by ingredient_id
    order by ingredient_id
  loop
    insert into public.inventory(warehouse_id,ingredient_id,quantity,updated_at)
    values(p_warehouse_id,v_item.ingredient_id,-coalesce(v_item.qty,0),now())
    on conflict(warehouse_id,ingredient_id) do update set
      quantity=public.inventory.quantity+excluded.quantity,updated_at=now();
  end loop;

  delete from public.stock_transactions
  where reference_id=p_reference_id and transaction_type='ADJUSTMENT';

  return true;
end;
$$;

grant execute on function public.commit_export_receipt_v192(uuid,uuid,uuid,jsonb,text)
to anon,authenticated;
grant execute on function public.delete_export_receipt_v192(uuid,uuid)
to anon,authenticated;
grant execute on function public.commit_stocktake_receipt_v192(uuid,uuid,uuid,jsonb,text)
to anon,authenticated;
grant execute on function public.delete_stocktake_receipt_v192(uuid,uuid)
to anon,authenticated;


COMMIT;

-- ============================================================
-- DONE
-- Required objects after success:
--   public.app_sync_state
--   public.app_operation_log
--   public.commit_app_sync_state(...)
--   public.commit_sale_receipt_v190(...)
--   public.commit_import_receipt_v191(...)
--   public.commit_export_receipt_v192(...)
--   public.delete_export_receipt_v192(...)
--   public.commit_stocktake_receipt_v192(...)
--   public.delete_stocktake_receipt_v192(...)
-- ============================================================


-- ============================================================
-- OPTIONAL VALIDATION
-- Run automatically as part of the script.
-- It returns the installed sync objects for quick verification.
-- ============================================================
select
  to_regclass('public.app_sync_state') as app_sync_state,
  to_regclass('public.app_operation_log') as app_operation_log;

select
  p.proname as function_name
from pg_proc p
join pg_namespace n on n.oid=p.pronamespace
where n.nspname='public'
  and p.proname in (
    'commit_app_sync_state',
    'commit_sale_receipt_v190',
    'commit_import_receipt_v191',
    'commit_export_receipt_v192',
    'delete_export_receipt_v192',
    'commit_stocktake_receipt_v192',
    'delete_stocktake_receipt_v192'
  )
order by p.proname;


-- V197 final search_path hotfix
alter function public.commit_app_sync_state(text,bigint,jsonb) set search_path = public, extensions;
alter function public.commit_sale_receipt_v190(jsonb,jsonb,jsonb,text) set search_path = public, extensions;
alter function public.commit_import_receipt_v191(uuid,uuid,jsonb,text) set search_path = public, extensions;
alter function public.commit_export_receipt_v192(uuid,uuid,uuid,jsonb,text) set search_path = public, extensions;
alter function public.delete_export_receipt_v192(uuid,uuid) set search_path = public, extensions;
alter function public.commit_stocktake_receipt_v192(uuid,uuid,uuid,jsonb,text) set search_path = public, extensions;
alter function public.delete_stocktake_receipt_v192(uuid,uuid) set search_path = public, extensions;
select extensions.digest('lat-yen-v197','sha256') is not null as pgcrypto_digest_ok;
