create table if not exists public.ly_activity_events (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.ly_organizations(id) on delete cascade,
  actor_user_id uuid null,
  entity_table text not null,
  entity_id uuid null,
  event_type text not null check (event_type in ('INSERT','UPDATE','DELETE')),
  entity_name text null,
  amount numeric null,
  created_at timestamptz not null default now()
);

alter table public.ly_activity_events enable row level security;

drop policy if exists ly_activity_select on public.ly_activity_events;
create policy ly_activity_select
on public.ly_activity_events
for select
to authenticated
using (
  ly_private.ly_is_admin()
  and org_id = ly_private.ly_current_org()
);

revoke all on table public.ly_activity_events from public, anon;
revoke insert, update, delete on table public.ly_activity_events from authenticated;
grant select on table public.ly_activity_events to authenticated, service_role;

create index if not exists idx_ly_activity_events_org_id_id
  on public.ly_activity_events(org_id, id desc);
create index if not exists idx_ly_activity_events_created_at
  on public.ly_activity_events(created_at desc);

create or replace function ly_private.ly_capture_activity_event()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_row jsonb;
  v_org uuid;
  v_id uuid;
  v_name text;
  v_amount numeric;
begin
  if tg_op = 'DELETE' then
    v_row := to_jsonb(old);
  else
    v_row := to_jsonb(new);
  end if;

  v_org := nullif(v_row->>'org_id','')::uuid;
  if v_org is null then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  v_id := nullif(v_row->>'id','')::uuid;
  v_name := coalesce(
    nullif(v_row->>'name',''),
    nullif(v_row->>'receipt_no',''),
    nullif(v_row->>'category',''),
    nullif(v_row->>'description',''),
    nullif(v_row->>'note','')
  );

  begin
    v_amount := nullif(coalesce(v_row->>'total_amount', v_row->>'amount', v_row->>'total'),'')::numeric;
  exception when others then
    v_amount := null;
  end;

  insert into public.ly_activity_events(
    org_id,
    actor_user_id,
    entity_table,
    entity_id,
    event_type,
    entity_name,
    amount
  ) values (
    v_org,
    auth.uid(),
    tg_table_name,
    v_id,
    tg_op,
    v_name,
    v_amount
  );

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

revoke all on function ly_private.ly_capture_activity_event() from public, anon, authenticated;
grant execute on function ly_private.ly_capture_activity_event() to service_role;

do $$
declare
  t text;
begin
  foreach t in array array[
    'ly_warehouses',
    'ly_suppliers',
    'ly_ingredients',
    'ly_products',
    'ly_import_receipts',
    'ly_export_receipts',
    'ly_stocktake_receipts',
    'ly_sales',
    'ly_cashflow_entries'
  ]
  loop
    execute format('drop trigger if exists ly_activity_event_trigger on public.%I', t);
    execute format(
      'create trigger ly_activity_event_trigger after insert or update or delete on public.%I for each row execute function ly_private.ly_capture_activity_event()',
      t
    );
  end loop;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'ly_activity_events'
  ) then
    alter publication supabase_realtime add table public.ly_activity_events;
  end if;
end $$;
